replicaCount: 2

image:
  repository: 533267351303.dkr.ecr.us-east-1.amazonaws.com/demo-app
  pullPolicy: IfNotPresent
  tag: "647ff9b783c0383a16119bff4ea7a229851579dc"

service:
  port: 3000

ingress:
  enabled: true
  host: demo.example.com 

resources: {}
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

